### ISSUE TITLE
Search stopped

### ISSUE THREAD

**Issue by jaredbidlow** [dodying/softwareUpdateManager#3]
Search doesn't begin as it did when I installed the app. I installed on a new user account and the same result:

C:\Users\Jbidl\softwareUpdateManager>node index.js -p lightscripts -s

- - - - - - - - - - -

**Comment by dodying** [comment]
if you config file like this
```
'use strict'
/* eslint-disable comma-dangle */

let config = {
  profile: {
    lightscripts:{
      // something here
    }
  }
}

module.exports = config
```


you can use `node index.js -p lightscripts`,
else just `node index.js`

**Comment by dodying** [comment]
search with keyword, like `-s chrome`

and, i find there a bug when search and fix it.

you need to git clone or fetch this repository to update

**Comment by dodying** [comment]
if you search, but do not find the software you want, you can tell me.
i may write the software script manually.

**Comment by jaredbidlow** [comment]
> search with keyword, like `-s chrome`
> 
> and, i find there a bug when search and fix it.

This fixes the search.

When I try the install mode, a new issue is that nothing happens:
`
C:\Users\Jbidl\softwareUpdateManager>node index.js -p lightscripts -i 163MusicLyrics

- - - - - - - - - - -
`

**Comment by dodying** [comment]
emm, `-i` mode work like restore.
for example:
config.js:`let config= { software:{ a:'path1', b:'path2', c:'path3' } }`
database.json: `{"a":{"version":"v1"},"b":{"version":"v2"}}`
in archive folder: `a-v1.exe`

`-i` mode will install software `a` version `v1` to `path1`

**Comment by dodying** [comment]
if you want to install software just use `node index.js`
and config.js `let config= { mode: 2, software: { '163MusicLyrics':'path|' } }`

**Comment by jaredbidlow** [comment]
I don't quite understand. Software should be installed before copying the path, which is not known until the install occurs. As such, the way I use this is to install any software from the folder with -i. I copy the path to set the config.js section, and then run node index.js. But this is not working. Installing does not download and unzip. It does nothing.

**Comment by dodying** [comment]
if you **know** the path, do like this: `folder|program.exe`
eg config.js `let config= { mode: 2, software: { '7-Zip': '7-Zip|7z.exe', } }`

don't know, you can set this: `folder|`
eg config.js `let config= { mode: 2, software: { '7-Zip': '7-Zip|', } }`

the `program.exe` just used when software don't record in file `database.json` to define which version, otherwise version get from `database.json`

**Comment by dodying** [comment]
```
  software: { // which software to use
    // key：software[:edition] (find in folder software or file SupportedSoftwares.md)
    // value：path (relative to rootPath, or you can use absolute path)
    '7-Zip': '7-Zip|7z.exe',

    // install folder and program file separator by '|'
    // for example，
    // install folder is "Epic"
    // program file is "Portal/Binaries/Win32/EpicGamesLauncher.exe"
    // if you don't know program file, replace with empty value "Epic|"
    //    or set as any string first time, and change it when software installed
    // Note: if program file is wrong (not empty value), it'll install software again and again when you run this script
    'Epic Games': 'Epic|Portal/Binaries/Win32/EpicGamesLauncher.exe',

    'Bandisoft/Bandizip:portable': 'Bandizip|Bandizip64.exe' // install portable  of Bandizip
  }
```
